### ISSUE TITLE
cookbook version + supermarket

### ISSUE THREAD

**Issue by rdoorn** [demonccc/chef-repo#12]
Hello, 

Since the redhat support fix the version was not updated, and the cookbook is not available in the supermarket
Would you be so kind as to update the version number, and upload it to the chef supermarket?

Thanks!

**Comment by demonccc** [comment]
Hi, what is the cookbooks that you need to upload in the Chef supermarket?

**Comment by rdoorn** [comment]
Hello,

its the Spamassassin cookbook, its currently in the supermarket with version 0.1.1, but that doesn't include the rhel7 fix, that is already in the git repository. so if you could up the version, and upload it to supermarket that would be great!

Kind Regards,
Ronald

**Comment by demonccc** [comment]
Hi, I created a new repository for the [spamassain cookbook](https://github.com/demonccc/chef-spamassassin) and I uploaded a new version of it to the Chef supermarket.

Regards.

**Comment by rdoorn** [comment]
Thanks!
